version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 1

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      ALLOW_PLAINTEXT_LISTENER: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: -Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
    depends_on:
      - "kafka"

  data-generator:
    build:
      context: .
      dockerfile: data-generator/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  data-analyzer:
    build:
      context: .
      dockerfile: data-analyzer/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - kafka
      - data-generator

  sms-notifier:
    build:
      context: .
      dockerfile: sms-notifier/Dockerfile
    ports:
      - "8083:8080"

  email-notifier:
    build:
      context: .
      dockerfile: email-notifier/Dockerfile
    ports:
      - "8084:8080"

  mobile-notifier:
    build:
      context: .
      dockerfile: mobile-notifier/Dockerfile
    ports:
      - "8085:8080"

  alarm-notifier:
    build:
      context: .
      dockerfile: alarm-notifier/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - sms-notifier
      - email-notifier
      - mobile-notifier

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local